import type { QuizVideoData } from './types';

export const mockQuizData: QuizVideoData = {
  title: "GENERAL KNOWLEDGE QUIZ",
  questions: [
    {
      id: 'q1',
      type: 'open',
      questionText: 'What is the capital of Australia?',
      questionNumber: 1,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Canberra',
    },
    {
      id: 'q2',
      type: 'image-open',
      questionText: 'Which country does this flag belong to?',
      questionNumber: 2,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Brazil',
      imageUrl: 'https://placeholder.com/brazil-flag.jpg',
    },
    {
      id: 'q3',
      type: 'open',
      questionText: 'In which year did the Berlin Wall fall, reuniting East and West Germany?',
      questionNumber: 3,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: '1989',
    },
    {
      id: 'q4',
      type: 'simple',
      questionText: 'Which movie is this scene from?',
      questionNumber: 4,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: 'The Godfather',
      options: ['Goodfellas', 'The Godfather', 'Scarface', 'Casino'],
      mediaUrl: 'https://clip.cafe/videos/dad-s357.mp4',
      mediaDuration: 8,
      mediaFit: 'contain',
      mediaRole: 'clue',
    },
    {
      id: 'q5',
      type: 'open',
      questionText: 'What is the longest river in the world?',
      questionNumber: 5,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: 'The Nile',
    },
    {
      id: 'q5b',
      type: 'simple',
      questionText: 'In which year was John Travolta born?',
      questionNumber: 5,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: '1954',
      options: ['1950', '1954', '1958', '1962'],
      mediaUrl: 'https://clip.cafe/videos/dad-s357.mp4',
      mediaRole: 'ambient',
      mediaFit: 'cover',
    },
    {
      id: 'q6',
      type: 'image-open',
      questionText: 'Name this famous landmark',
      questionNumber: 6,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Machu Picchu',
      imageUrl: 'https://placeholder.com/machu-picchu.jpg',
    },
    {
      id: 'q7',
      type: 'open',
      questionText: 'Which English footballer scored a hat-trick in the 1966 World Cup Final against West Germany?',
      questionNumber: 7,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Geoff Hurst',
    },
    {
      id: 'q8',
      type: 'simple',
      questionText: 'When did the London Underground first open?',
      questionNumber: 8,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: '1863',
      options: ['1843', '1863', '1890', '1905'],
      mediaUrl: 'https://clip.cafe/videos/dad-s357.mp4',
      mediaFit: 'cover',
      mediaRole: 'ambient',
    },
    {
      id: 'q9',
      type: 'image-open',
      questionText: 'Which animal is this?',
      questionNumber: 9,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Pangolin',
      imageUrl: 'https://placeholder.com/pangolin.jpg',
    },
    {
      id: 'q10',
      type: 'open',
      questionText: 'What was the name of the ship that Charles Darwin sailed on during his famous voyage to the Galapagos Islands?',
      questionNumber: 10,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: 'HMS Beagle',
    },
    {
      id: 'q11',
      type: 'audio',
      questionText: 'Name the artist who performed this famous song',
      questionNumber: 11,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: 'Queen',
      audioTitle: '🎵 LISTEN CAREFULLY...',
      options: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'],
      mediaUrl: 'https://clip.cafe/videos/dad-s357.mp4',
      mediaDuration: 10,
    },
    {
      id: 'q12',
      type: 'image-options',
      questionText: 'Which painting is by Vincent van Gogh?',
      questionNumber: 12,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: 'Starry Night',
      options: ['The Scream', 'Starry Night', 'Girl with a Pearl Earring'],
      optionImages: [
        'https://images.pexels.com/photos/3246665/pexels-photo-3246665.jpeg?auto=compress&cs=tinysrgb&w=800',
        'https://images.pexels.com/photos/1269968/pexels-photo-1269968.jpeg?auto=compress&cs=tinysrgb&w=800',
        'https://images.pexels.com/photos/1585325/pexels-photo-1585325.jpeg?auto=compress&cs=tinysrgb&w=800',
      ],
      correctIndex: 1,
    },
    {
      id: 'q13',
      type: 'this-or-that',
      questionText: 'Which country has a larger population?',
      questionNumber: 13,
      totalQuestions: 14,
      timeLimit: 7,
      correctAnswer: 'Turkey',
      optionA: 'Germany',
      optionB: 'Turkey',
      imageA: 'https://images.pexels.com/photos/109629/pexels-photo-109629.jpeg?auto=compress&cs=tinysrgb&w=800',
      imageB: 'https://images.pexels.com/photos/2064827/pexels-photo-2064827.jpeg?auto=compress&cs=tinysrgb&w=800',
      correctSide: 'B',
    },
    {
      id: 'q14',
      type: 'this-or-that',
      questionText: 'Which building is taller?',
      questionNumber: 14,
      totalQuestions: 14,
      timeLimit: 7,
      correctAnswer: 'Eiffel Tower',
      optionA: 'Big Ben',
      optionB: 'Eiffel Tower',
      imageA: 'https://images.pexels.com/photos/77171/pexels-photo-77171.jpeg?auto=compress&cs=tinysrgb&w=800',
      imageB: 'https://images.pexels.com/photos/338515/pexels-photo-338515.jpeg?auto=compress&cs=tinysrgb&w=800',
      correctSide: 'B',
    },
  ],
};
