import type { QuizVideoData } from './types';

export const mockQuizData: QuizVideoData = {
  title: "GENERAL KNOWLEDGE QUIZ",
  questions: [
    {
      id: 'q1',
      type: 'open',
      questionText: 'What is the capital of Australia?',
      questionNumber: 1,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Canberra',
    },
    {
      id: 'q2',
      type: 'image-open',
      questionText: 'Which country does this flag belong to?',
      questionNumber: 2,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Brazil',
      imageUrl: 'https://placeholder.com/brazil-flag.jpg',
    },
    {
      id: 'q3',
      type: 'open',
      questionText: 'In which year did the Berlin Wall fall, reuniting East and West Germany?',
      questionNumber: 3,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: '1989',
    },
    {
      id: 'q4',
      type: 'simple',
      questionText: 'Which planet in our solar system has the most moons?',
      questionNumber: 4,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Saturn',
      options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    },
    {
      id: 'q5',
      type: 'open',
      questionText: 'What is the longest river in the world?',
      questionNumber: 5,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'The Nile',
    },
    {
      id: 'q6',
      type: 'image-open',
      questionText: 'Name this famous landmark',
      questionNumber: 6,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Machu Picchu',
      imageUrl: 'https://placeholder.com/machu-picchu.jpg',
    },
    {
      id: 'q7',
      type: 'open',
      questionText: 'Which English footballer scored a hat-trick in the 1966 World Cup Final against West Germany?',
      questionNumber: 7,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Geoff Hurst',
    },
    {
      id: 'q8',
      type: 'simple',
      questionText: 'What is the chemical symbol for gold?',
      questionNumber: 8,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Au',
      options: ['Go', 'Au', 'Gd', 'Ag'],
    },
    {
      id: 'q9',
      type: 'image-open',
      questionText: 'Which animal is this?',
      questionNumber: 9,
      totalQuestions: 10,
      timeLimit: 10,
      correctAnswer: 'Pangolin',
      imageUrl: 'https://placeholder.com/pangolin.jpg',
    },
    {
      id: 'q10',
      type: 'open',
      questionText: 'What was the name of the ship that Charles Darwin sailed on during his famous voyage to the Galapagos Islands?',
      questionNumber: 10,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: 'HMS Beagle',
    },
    {
      id: 'q11',
      type: 'audio',
      questionText: 'Name the artist who performed this famous song',
      questionNumber: 11,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: 'Queen',
      audioTitle: '🎵 BOHEMIAN RHAPSODY',
      options: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'],
    },
    {
      id: 'q12',
      type: 'image-options',
      questionText: 'Which painting is by Vincent van Gogh?',
      questionNumber: 12,
      totalQuestions: 12,
      timeLimit: 10,
      correctAnswer: 'Starry Night',
      options: ['The Scream', 'Starry Night', 'Girl with a Pearl Earring'],
      optionImages: ['https://placeholder.com/scream.jpg', 'https://placeholder.com/starry-night.jpg', 'https://placeholder.com/girl-pearl.jpg'],
      correctIndex: 1,
    },
  ],
};
